package com.navigo3.dryapi.core.exec;

public enum ResponseStatus {
	SUCCESS,
	NOT_FOUND,
	NOT_AUTHORIZED,
	INTERNAL_ERROR_ON_SECURITY,
	INTERNAL_ERROR_ON_VALIDATION,
	INTERNAL_ERROR_ON_EXECUTION,
	INTERNAL_ERROR_ON_CLEARING_INPUT,
	INTERNAL_ERROR_ON_CLEARING_OUTPUT,
	INVALID_INPUT,
	MALFORMED_INPUT,
	NOT_PROCESSED_DUE_TO_PREVIOUS_ERRORS,
	METHOD_NOT_ALLOWED
}
